apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:14.24-alpine3.23
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "axion"
        - name: POSTGRES_PASSWORD
          value: "axion@123"
        - name: POSTGRES_DB
          value: "axiondb"